---
title: "Simple document"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

let's import 'FAS_litters.csv' csv using a relative path.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df)
#janitor is a package in R -- can load entire package if we want using library(), but it loads all functions in the janitor package

```
important Pups dataset
```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df = 
  janitor::clean_names(pups_df)
```

## look at data 

```{r}
litters_df

head(litters_df)

tail(litters_df)
```
you can use 'view'

```{r, eval = FALSE}
view(litters_df)
#don't include view function in your rmarkdown files
```

look at a data summary
```{r}
str(litters_df)

skimr::skim(litters_df)
#can be helpful to read dataset 
```
## options in read_*

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
     skip = 10, col_names = FALSE)
#skipping the first 10 columns, R assuumes that your first row is your variable name
```
look at NA values

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
      na = c("NA", 19))
```
column types 

```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    col_types =
      cols(
        'GD0 weight' = col_character()
      ))
```

## other file types

important a xlsx file first 

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

import a SAS file 

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")
```

## export data 

we have code that "cleans" data and need to export 

```{r}
litters_df_cleaned = 
  read_csv("data/FAS_litters.csv")

litters_df_cleaned =
  janitor::clean_names(litters_df_cleaned)

write_csv(litters_df_cleaned, "data/litters_cleaned.csv")
```



