---
title: "tidy data"
output: github_document
---

```{r}
library(tidyverse)
```


## focus on `pivot_longer` function
load the PULSE data
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

wide format to long format 
```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
    )
```

## putting everything in a single code chunk
rewrite, combine, and extend (to add a mutate step)
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
    ) %>% 
  relocate (id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```

## using `pivot_wider` function 
going from wide format to long format 

make up some data! 

```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"), 
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

